dist: xenial
language: bash
sudo: true
services:
  - docker
branches:
  only:
    - master
env:
  global:
    - IMAGE_NAME="danielchoi158/portfolio-frontend"
    - secure: oKBd7qmRksIdp6CCkALHLAcsPY9mcxqBv7SG+jEzqVYUgl5c2Rw9wbnswJzMlW2wMAxD0HRtS/d7+oueU+GY+69oSM2vd3GqXYJyhwQB6KykuZBX4mrZHW2sv24AMq61oBeZLKTiVNaBTB6Zb5SGjJZ8LVNYcrringGMEfSn4OaQ9X0UO8oKcv/DGVLqurPZNaJ+uQ52TK9ACOLrXFEul6lglXkRTOaBpeyP6S/32PtNUIxSuJH11Mi2xW51Nn6GqcPHcPIcKU16+5814TCJuTzODufnOSv9Dubo/gg3F/v2g7zlgpHoZH55noVJFyFnRI/z5LNmU5rOwcL/+ijI2lL+ekdMnEX9GDlwuoz6kIhR9V2+I58b8+lNRe4JZwkURyd0lFYnlfV2x/lc+uM7Kxq3aw/cpXp4PQ0s4TxPyfj2byZ14Zv/HI/JmNhD6NchrjovOVtDY3YDy8VAqJ2oOPnXCFgfUdsZ4QMAbBYZ+PQFl/Zb5FtByQxJujRE4M2wPaUd1EkpsWF6v7cHMJNeTWGMcV3oXrqFchu93B+BqDPmGorZJmVVrOqGVM8CoNfoJrqfTE+zHtVY9Lq2CDclr8B9lvqEi5wcBzrIN3WzB5RTxxiqyRI83gLsSH4BG7Wr2PqLAc0MyTt6cjnalhL2MLHN3HpajMwTwMwzJ/l3P58=
    - secure: neWLjmCxPTJfMTkR4Rpb4KtRZxE3+i/7CrWgS2TQhu8zk+dmGhPdfYOevDzWieSEbCIL0CYjDnFq07HAMy4Mx81HQpiuqS1smVS7rOVBw/ovzDrIKP6x2HXxy7GLwxHOQbumUflXerJr4hLsNZ0R7W9lZZY2zfIHZ9nws0niKApHR1ykmpEdHP4O8S2rCZmNuJFj1rOzswpEstglhQpLhlhlR0GrVz+FU8m4xp6MDTE+yrqBSP/egtmTVabvzh7i067Mo+ijSSGowHYNwIVlbTocDp1bo8rTRAO7bKnSz5FvoNLXB5Zu3W09ixSCrUcuI6uoWGPvwkvuwdqt8RHjJvlc4OEScT5VOu0VABl8cZd2YytOUTfoeYzfaKADBGFA9Uv1HqxGYV2WhTOzgBOQevZDLB9DjVg6OPOdtK7MfB3cSqGGF5AZp1L2f6T5+dQCGUCZ3JffVRwJGv9OQYcPcU8wcG976c0K8DU7LybNq3z47iWsBSHOrtbXkOyQoRzIf40l4H91iMzH6Idw67/n19wMwIuI2Ru5x0RMjLwHlKDBvrmD+IMnvTEYJOifA1orAGUEYI6Bjsdc0gSv5WxOCOtza5Av/Kg67W9o1M54SCCDFykALGE5p9xF4EQPllq364MMFPOIi8jFPs66urWpuI+XV/X96M69r6prQKLqvkI=
before_script:
  - cd frontend/
  - version="$(awk '$2 == "CAKE_SERVICE_VERSION" { print $3; exit }' Dockerfile)"
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
after_script:
  - docker images
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
