dist: xenial
language: bash
services:
  - docker
branches:
  only:
    - master
env:
  global:
    - IMAGE_NAME="danielchoi158/portfolio-frontend"
    - SHORT_SHA="$(git log -1 --pretty=%h)"
    - CLUSTER_NAME="tf-webapp-268705-gke"
    - GCLOUD_ZONE="australia-southeast1-a"
    - GCLOUD_PROJECT="tf-webapp-268705"
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
# Install and configure dependencies (gcloud, kubectl)
before_install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  - echo $GCLOUD_SERVICE_KEY_TRAVISCI | base64 --decode -i > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json

jobs:
  include:
    - stage: portfolio-frontend - build, tag, push image
      if: type IN (push) and branch = master
      script:
        - docker pull "$IMAGE_NAME" || true
        - cd ./frontend/
        - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
        - docker image ls
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${SHORT_SHA}"
        - docker push "${IMAGE_NAME}:${SHORT_SHA}"
    - stage: portfolio-frontend - test
      script: docker run --rm ${IMAGE_NAME}:${SHORT_SHA} echo hi
    - stage: portfolio-frontend - deploy image
      script:
        - gcloud config set compute/zone ${GCLOUD_ZONE}
        - gcloud config set project ${GCLOUD_PROJECT}
        - gcloud container clusters get-credentials ${CLUSTER_NAME}
        - kubectl rollout restart deployment portfolio-frontend-deployment
        - kubectl get deployments
        - kubectl get pods
        - kubectl get service
